/** Shared presentation-only catalog: never inserted into a store or used as authority. */
export const COLLECTION_STATE_FIXTURES = [
  { key: "signed-out", label: "Signed out", description: "No X session. Sign in before accessing a private collection." },
  { key: "empty", label: "No claims", description: "Signed in as @newcomer, with no claims. The prompt uses this site’s origin." },
  { key: "gallery-claimed-empty", label: "Claimed · empty", description: "The public Claimed gallery has no works. Participation guidance does not assume a signed-in account." },
  { key: "gallery-minted-empty", label: "Minted · empty", description: "The public Minted gallery has no finalized works. Participation guidance is available before sign-in." },
  { key: "claimed", label: "Claimed · connect wallet", description: "The claim needs no wallet. The active claimant session can connect a wallet and prove control for this mint without another X sign-in." },
  { key: "wallet-linked", label: "Previous recipient", description: "A previous recipient is only a convenience. This new mint still requires a fresh wallet proof, without another X sign-in for an active claimant session." },
  { key: "recipient-verified", label: "Recipient verified", description: "The original claimant session and fresh wallet proof match this exact mint. Review the work, recipient, and fees next." },
  { key: "wrong-claimant", label: "Wrong claimant", description: "The signed-in X account is not the original claimant. Recipient controls remain unavailable." },
  { key: "authorized", label: "Awaiting wallet", description: "Authorization exists. No confirmed mint yet." },
  { key: "submitted", label: "Submitted", description: "A transaction was submitted; it is not yet a finalized mint." },
  { key: "confirming", label: "Confirming", description: "Included in a block, but awaiting finality." },
  { key: "minted", label: "Minted", description: "A finalized mint, held by the initial recipient. Open Provenance to inspect the fixture references." },
  { key: "transferred", label: "Transferred", description: "Still the original claimant’s signature. The token’s current holder is another wallet." },
  { key: "validation-pending", label: "Verification pending", description: "The claim stays visible while mint evidence is checked." },
  { key: "quarantined", label: "Review required", description: "Conflicting mint evidence requires review; no finalized status is asserted." },
  { key: "finality-revoked", label: "Finality incident", description: "A previously finalized mint has lost its confirmation. The claim is unchanged." },
  { key: "mint-paused", label: "Minting paused", description: "Minting is unavailable. Existing claims remain readable. No recipient connection or changes are offered." },
  { key: "reauthenticate", label: "Active session · connect wallet", description: "Legacy fixture URL. The active claimant session goes directly to wallet connection; there is no routine X reauthentication step." },
  { key: "renamed", label: "Handle changed", description: "The account is now @alice_studio. The historical claim remains @alice." },
] as const;
