import { createHash } from "node:crypto";
import { SITE_FONT_CSS } from "./fonts.js";

export const SITE_CSS = `
${SITE_FONT_CSS}
:root{--ui-font-size:14px;--control-padding:3px 7px;--control-line-height:1.35;--tag-padding:1px 3px;--tag-radius:4px;--font-family:"Instrument Sans",sans-serif;color-scheme:light;--collection-dot:#000;--ink:#101319;--paper:#f4f0e6;--paper-2:#e7e0d2;--blue:#2557ff;--blue-hover:#153fe0;--line:rgba(16,19,25,.18);--muted:#625f59;--white:#fffdf8;--stage:#d9dce5;--art-paper:#f4e7c7;--art-shadow:rgba(16,19,25,.16)}
@media(prefers-color-scheme:dark){:root{color-scheme:dark;--collection-dot:#fff;--ink:#f4f0e6;--paper:#101319;--paper-2:#242832;--blue:#7893ff;--blue-hover:#91a7ff;--line:rgba(244,240,230,.2);--muted:#aaa7a0;--white:#171b22;--stage:#242832;--art-paper:#f4e7c7;--art-shadow:rgba(0,0,0,.42)}}
*{box-sizing:border-box}html{font-size:16px}body{margin:0;background:var(--paper);color:var(--ink);font-family:var(--font-family);min-height:100vh}button,input,select,textarea{font:inherit}code,pre,kbd,samp{font-family:var(--font-family)}a{color:inherit}
.book-page{position:relative;width:100%;max-width:1024px;margin-inline:auto;--page-gutter:32px}.book-page footer{padding-inline:var(--page-gutter);flex-wrap:wrap;gap:.5rem 1rem}
.collection-shortcut{position:absolute;inset-block-start:max(.75rem,env(safe-area-inset-top));inset-inline-end:max(.75rem,env(safe-area-inset-right));z-index:10;display:grid;place-items:center;width:44px;height:44px;border-radius:50%;color:var(--collection-dot);text-decoration:none}.collection-shortcut-dot{display:block;width:10px;height:10px;border-radius:50%;background:currentColor}.collection-shortcut:focus-visible{outline:2px solid var(--blue);outline-offset:2px}
.account-menu{position:absolute;inset-block-start:max(.75rem,env(safe-area-inset-top));inset-inline-end:max(.75rem,env(safe-area-inset-right));z-index:30;width:44px;height:44px}.account-menu .collection-shortcut{inset:0}.account-panel{position:absolute;inset-block-start:100%;inset-inline-end:0;width:336px;max-width:calc(100vw - 32px);max-height:calc(100dvh - 80px);overflow-y:auto;overscroll-behavior:contain;padding:16px;background:var(--paper);border:1px solid var(--line);color:var(--ink);line-height:1.5;visibility:hidden;pointer-events:none;overflow-wrap:anywhere}.account-menu:hover .account-panel,.account-menu:focus-within .account-panel{visibility:visible;pointer-events:auto}.account-menu[data-panel-ready] .account-panel{visibility:hidden;pointer-events:none}.account-menu[data-open="true"] .account-panel{visibility:visible;pointer-events:auto}.account-panel-section+.account-panel-section{margin-top:1rem}.account-panel-row{display:flex;align-items:center;flex-wrap:wrap;gap:.25rem .75rem;min-height:32px}.account-panel-row h3{margin:0;color:var(--muted)}.account-panel-row form{margin-inline-start:auto}.account-panel p{margin:.4rem 0}.account-panel .auth-actions{margin-top:.25rem;gap:8px .75rem}.account-panel .inline-feedback{min-height:0;color:var(--muted);font:inherit}.account-panel .inline-feedback:empty{margin:0}.account-panel .reauth-button{min-height:44px;font:inherit}.account-panel [aria-busy="true"]{opacity:.6;pointer-events:none}.account-menu-toggle{display:none;position:absolute;inset-inline-end:44px;inset-block-start:0;width:44px;height:44px;align-items:center;justify-content:center;padding:0;border:0;background:transparent;color:var(--muted);cursor:pointer}.account-menu-toggle:focus-visible{outline:2px solid var(--blue);outline-offset:2px}
.account-panel-heading{margin:0 0 .75rem;line-height:1.5}
.account-panel-heading a{text-decoration:none}.account-panel-heading a:hover{text-decoration:underline;text-underline-offset:.15em}.account-panel-heading a:focus-visible{outline:2px solid var(--blue);outline-offset:3px}
@media(hover:none),(pointer:coarse){.account-menu-toggle{display:flex}}
main{min-height:calc(100vh - 64px)}.home-grid{display:grid;grid-template-columns:minmax(0,1fr);grid-template-rows:auto 1fr;min-height:calc(100vh - 64px)}.intro-panel{display:grid;place-items:center;padding:clamp(2.5rem,4vw,4rem) var(--page-gutter,32px);padding-block-start:4rem}
.eyebrow,.art-label{line-height:1.2;letter-spacing:.12em;text-transform:uppercase}.eyebrow{color:var(--blue);margin:0 0 1.25rem}.eyebrow a{text-decoration:none}.eyebrow a:hover{text-decoration:underline}h1{font-family:var(--font-family);line-height:1.5;letter-spacing:normal;margin:0;max-width:none}.lede{line-height:1.55;max-width:40rem;margin:0 0 1rem;color:var(--muted)}.lede code{color:var(--ink)}
.visually-hidden{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap;border:0}
.slogan-tooltip,.action-tooltip{position:fixed;z-index:100;left:0;top:0;max-width:calc(100vw - 16px);padding:6px 8px;background:var(--white);color:var(--ink);border:1px solid var(--line);border-radius:4px;box-shadow:0 3px 12px var(--art-shadow);line-height:1.4;overflow-wrap:anywhere;cursor:text}.slogan-tooltip[hidden],.action-tooltip[hidden]{display:none}.action-tooltip{width:320px;text-align:start;cursor:default}
.slogan-lockup{width:100%;max-width:42rem}.slogan-signature{width:100%;margin:0;color:var(--ink);cursor:text}.slogan-signature:focus-visible{outline:2px solid var(--blue);outline-offset:4px}.slogan-signature-layout{display:block}.slogan-signature-layout svg{display:block;width:100%;height:auto;overflow:visible}.slogan-signature-mobile{display:none;width:100%}
.slogan-signature[data-tooltip-ready="true"]{cursor:default}.slogan-signature[data-tooltip-ready="true"][data-tooltip-hover="true"]{cursor:text}
.local-wallet-address{display:block;line-height:1.5;overflow-wrap:anywhere}
.gallery-shell{color:var(--ink);padding:2rem var(--page-gutter,32px);display:flex;flex-direction:column}
details{margin-top:2rem}summary{cursor:pointer}pre{white-space:pre-wrap;background:var(--white);border:1px solid var(--line);padding:1.25rem;line-height:1.5;max-width:44rem;overflow:auto}
.art-label{display:flex;justify-content:space-between;margin-bottom:1rem}.trust-copy,.fine-print{line-height:1.55;color:var(--muted);max-width:32rem}.fine-print{margin-top:1rem}
.button{appearance:none;display:inline-flex;justify-content:center;align-items:center;max-width:100%;background:transparent;color:var(--ink);border:1px solid var(--ink);border-radius:2px;padding:var(--control-padding);font:inherit;line-height:var(--control-line-height);text-align:center;text-decoration:none;cursor:pointer;transition:background-color 120ms,color 120ms,transform 120ms}.button:not(:disabled):hover{background:var(--ink);color:var(--paper)}.button.secondary{background:transparent;color:inherit;border-color:currentColor;margin-top:1rem}
.facts{margin:2rem 0;border-top:1px solid var(--line)}.facts>div{display:grid;grid-template-columns:minmax(8rem,.5fr) 1fr;gap:1rem;padding:.8rem 0;border-bottom:1px solid var(--line)}.facts dt{text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}.facts dd{margin:0;line-height:1.45;overflow-wrap:anywhere}.notice{border-left:3px solid var(--blue);padding:.2rem 0 .2rem 1rem;margin:1rem 0}.notice p{color:var(--muted);line-height:1.5}.quiet-link{margin-top:1.2rem;color:var(--muted)}.provenance{margin-top:1rem}.provenance-note{max-width:34rem;margin:1.1rem 0 0;color:var(--muted);line-height:1.55}.provenance-note code{color:var(--ink)}
.collection-page{padding:5rem var(--page-gutter) 3rem;line-height:1.6;overflow-wrap:anywhere}.collection-intro{width:100%}.collection-head{display:flex;align-items:center;justify-content:space-between;gap:1rem}.collection-intro p{margin:.5rem 0}.collection-grid{padding:2rem 0 0;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));align-items:start;gap:2rem clamp(1rem,2vw,2rem)}.signature-card{display:block;text-decoration:none}.signature-card img{display:block;width:100%;aspect-ratio:1;background:var(--art-paper)}.signature-card>div{display:grid;grid-template-columns:minmax(0,1fr) auto;margin-top:.8rem;gap:.25rem .75rem;line-height:1.35}.signature-card span,.signature-card time{color:var(--muted)}.signature-card time{grid-column:2;grid-row:1}.signature-art-link{display:block}.signature-art-link:focus-visible{outline:2px solid var(--blue);outline-offset:3px}.collection-empty{grid-column:1/-1;padding:3rem 0;color:var(--muted)}.collection-empty h2,.collection-empty p{margin:0 0 .5rem}
.collection-empty{width:100%;max-width:42rem;margin-inline:0;padding:0}.participation{width:100%;max-width:42rem;margin-inline:0;line-height:1.6}.participation .grok-intro{margin:0}.signed-out-participation{padding:2rem 0}.grok-prompt{display:block;width:100%;margin:.5rem 0 1rem;padding:.75rem;border:1px solid var(--line);border-radius:2px;background:transparent;color:var(--ink);line-height:1.6;resize:vertical;overflow-wrap:anywhere}.grok-prompt:focus-visible{outline:2px solid var(--blue);outline-offset:3px}.participation a{text-underline-offset:.2em}.participation .auth-action[hidden]{display:none}
.auth-sheet.collection-sheet{max-width:none}.collection-intro .signature-heading{line-height:1.5}.collection-sheet .signature-heading h1{line-height:1.5}
.grok-intro,.grok-steps{color:var(--ink)}.grok-step-copy .grok-step-arrow{padding:0;margin-inline-start:4px;background:transparent}.grok-step-action .inline-feedback{min-height:0;margin:0;color:var(--muted);line-height:1.6}
.grok-steps{list-style:none;margin:1rem 0;padding:0;display:grid;gap:.75rem}.grok-steps>li{display:grid;grid-template-columns:max-content minmax(0,1fr);gap:.5rem}.grok-step-label{padding-block:11px}.grok-step-action{display:flex;align-items:center;flex-wrap:wrap;gap:0 .75rem;min-height:44px}.grok-step-action .inline-feedback:not(:empty){margin:0}.grok-prompt-disclosure{margin:0}.grok-prompt-disclosure summary{display:list-item;width:fit-content;min-height:44px;padding-block:11px}.grok-step-copy{line-height:1.6}.grok-step-copy .auth-action{vertical-align:middle}.grok-local-sample{display:inline-flex;align-items:center;min-height:44px;text-decoration:none}.grok-local-sample:hover{text-decoration:underline}
.preview-controls{border:0;margin:0;padding:0;min-width:0}
.mint-entry-art{display:block;width:min(100%,240px);height:auto;aspect-ratio:1;margin:1rem 0;background:var(--art-paper)}.mint-entry-steps{margin:1rem 0;padding-inline-start:1.25rem;line-height:1.8}.signature-mint-entry{margin-top:1rem}.signature-mint-entry p{margin:.25rem 0;line-height:1.5}
.public-gallery-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:clamp(1rem,2vw,2rem);margin:auto 0;padding:3rem 0}.gallery-card{color:var(--ink);text-decoration:none;padding-top:.65rem;display:block}.gallery-card img{display:block;width:100%;aspect-ratio:1;background:var(--art-paper)}.gallery-card-copy{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:baseline;gap:.25rem .75rem;padding-top:.8rem}.gallery-card-copy>span,.gallery-card-copy small{line-height:1.35;color:var(--muted)}.gallery-card-copy>strong{grid-column:1;grid-row:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.gallery-card-copy>span{grid-column:2;grid-row:1;white-space:nowrap}.gallery-card-copy small{grid-column:1/-1}.gallery-item{min-width:0}.gallery-card:focus-visible{outline:2px solid var(--blue);outline-offset:3px}.gallery-more{align-self:flex-end;margin:-1rem 0 2rem;color:var(--ink);line-height:1.4;text-underline-offset:.2em}
.wallet-wrap{min-width:0}.wallet-option{padding:.5rem 0;min-width:0}.wallet-option p:first-child{color:var(--ink)}.collection-card{min-width:0}.mint-card-foot{display:flex;align-items:center;flex-wrap:wrap;justify-content:space-between;gap:.25rem .5rem;min-height:44px;padding:.5rem 0 0}.mint-card-detail{display:grid;justify-items:start;gap:.35rem;color:var(--muted);line-height:1.5}.mint-card-detail>*{min-width:0;max-width:100%;overflow-wrap:anywhere}.mint-card-detail a{text-underline-offset:.2em}.collection-page .inline-feedback{min-height:0;margin:0;color:var(--muted);line-height:1.6}.collection-page .inline-feedback:not(:empty){margin:.5rem 0}.collection-page .reauth-button{min-height:44px;background:transparent;border:0;padding:3px;color:var(--ink);font:inherit}.collection-page .reauth-button:focus-visible{outline:2px solid var(--blue);outline-offset:3px}
.text-button{appearance:none;border:0;border-bottom:1px solid currentColor;background:transparent;color:var(--muted);padding:.25rem 0;cursor:pointer}.text-button:hover{color:var(--ink)}.inline-feedback{min-height:1.4em;color:var(--blue);line-height:1.4}.inline-feedback .reauth-button{margin-left:.35rem}
[data-x-action-feedback]{min-height:0;margin:.5rem 0 0}[data-x-action-feedback]:empty{margin:0}
.mint-review{display:grid;grid-template-columns:minmax(320px,1fr) minmax(440px,.9fr);min-height:calc(100vh - 64px)}.mint-art{background:var(--stage);padding:5vw;display:flex;flex-direction:column;justify-content:center}.mint-art img{display:block;width:min(100%,620px);aspect-ratio:1;align-self:center;background:var(--art-paper);box-shadow:0 28px 70px var(--art-shadow)}.mint-review-copy{padding:clamp(2.5rem,5vw,5rem);background:var(--white)}.permanence{border:1px solid var(--blue);border-left-width:5px;padding:1.1rem 1.25rem}.permanence p{margin-bottom:0}.consent-line{display:flex;align-items:flex-start;gap:.7rem;margin:1.5rem 0;line-height:1.45;cursor:pointer}.consent-line input{width:1.1rem;height:1.1rem;margin-top:.1rem;accent-color:var(--blue)}
.gallery-return{position:absolute;inset-block-start:max(.75rem,env(safe-area-inset-top));inset-inline-start:max(.75rem,env(safe-area-inset-left));display:grid;place-items:center;width:44px;height:44px;color:var(--collection-dot);text-decoration:none}
.home-return{z-index:10}.home-icon{display:block;width:11px;height:11px;flex:none}
.signature-page{padding:5rem var(--page-gutter) 3rem}.signature-sheet{width:100%;max-width:42rem;margin-inline:auto}.signature-art{margin:0}.signature-art img{display:block;width:100%;height:auto;aspect-ratio:1;background:var(--art-paper)}.signature-record{padding-top:1rem;line-height:1.5}.signature-heading{display:flex;align-items:center;flex-wrap:wrap;gap:.5rem 1rem}.signature-heading h1{margin:0;max-width:none;line-height:1.5;letter-spacing:normal;overflow-wrap:anywhere}.signature-gr0k{color:var(--muted);font-variant-numeric:tabular-nums}.signature-tags{display:flex;align-items:center;flex-wrap:wrap;gap:.5rem;margin-inline-start:auto}.signature-tag{display:inline-flex;align-items:center;justify-content:center;max-width:100%;padding:var(--tag-padding);border:0;border-radius:var(--tag-radius);line-height:var(--control-line-height);background:var(--paper-2);color:var(--ink)}.signature-pending{color:var(--muted)}
.signature-tools{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:0 1.5rem;margin-top:.5rem}.signature-provenance{grid-column:1/-1;grid-row:1;min-width:0;margin:0}.signature-provenance>summary{width:fit-content;max-width:calc(100% - 64px);min-height:44px;padding:13px 0;line-height:18px;list-style-position:inside;color:var(--muted)}.signature-svg{grid-column:2;grid-row:1;align-self:start;display:flex;align-items:center;justify-content:flex-end;min-height:44px;min-width:44px;color:var(--muted);text-decoration:none}.signature-svg:hover,.signature-provenance>summary:hover{color:var(--ink)}.gallery-return:focus-visible,.signature-svg:focus-visible,.signature-provenance>summary:focus-visible,.signature-provenance-body a:focus-visible{outline:2px solid var(--blue);outline-offset:3px}
.signature-provenance-body{padding-top:.75rem;overflow-wrap:anywhere}.signature-provenance-section{margin:0 0 2rem}.signature-provenance-section h2{margin:0 0 .75rem;line-height:1.5}.signature-provenance-section p{margin:.75rem 0;color:var(--muted);line-height:1.6}.signature-facts{display:grid;gap:.6rem;margin:1rem 0}.signature-facts>div{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,2fr);gap:1rem}.signature-facts dt{color:var(--muted)}.signature-facts dd{margin:0;min-width:0;overflow-wrap:anywhere;font-variant-numeric:tabular-nums}.signature-facts a{text-underline-offset:.2em}
.auth-page{padding:5rem var(--page-gutter) 3rem}.auth-sheet{width:100%;max-width:42rem;margin-inline:auto;line-height:1.6;overflow-wrap:anywhere}.auth-sheet h1{max-width:none;margin:0;line-height:1.6;letter-spacing:normal}.auth-sheet p{margin:.75rem 0}.auth-note{color:var(--muted)}
.claim-action{scroll-margin-top:5rem;color:var(--ink)}.claim-action .auth-actions{margin-top:0}
.claim-toast{position:fixed;z-index:60;inset-inline-start:50%;bottom:max(20px,env(safe-area-inset-bottom));transform:translateX(-50%);display:flex;align-items:center;gap:8px;width:max-content;max-width:min(480px,calc(100vw - 32px));padding:8px 8px 8px 16px;border:1px solid var(--line);border-radius:4px;background:var(--white);color:var(--ink);box-shadow:0 4px 20px var(--art-shadow);line-height:1.5}.claim-toast[hidden]{display:none}.claim-toast p{margin:0;min-width:0}.claim-toast button{display:grid;place-items:center;flex:0 0 44px;width:44px;height:44px;padding:0;border:0;background:transparent;color:inherit;cursor:pointer}.claim-toast button:hover{background:var(--paper-2)}.claim-toast button:focus-visible{outline:2px solid var(--ink);outline-offset:-4px}
.auth-actions{display:flex;align-items:center;flex-wrap:wrap;gap:8px 1rem;margin-top:.75rem}.auth-action{appearance:none;display:inline-flex;align-items:center;justify-content:center;min-height:44px;min-width:44px;max-width:100%;padding:0;border:0;background:transparent;color:var(--ink);font:inherit;line-height:var(--control-line-height);text-align:center;text-decoration:none;cursor:pointer;transition:transform 120ms}
/* Compact visible labels inside 44px click targets, like the home tabs.
   Paint only the label so external-link arrows remain outside the button. */
.auth-action>span:first-child{display:inline-flex;align-items:center;justify-content:center;min-width:0;max-width:100%;padding:var(--control-padding);border:1px solid var(--ink);border-radius:2px;background:transparent;color:var(--ink);line-height:var(--control-line-height);transition:background-color 120ms,color 120ms}
.auth-action:not(:disabled):hover>span:first-child{background:var(--ink);color:var(--paper)}
.auth-action:not(:disabled):active,.button:not(:disabled):active{transform:translateY(1px)}
.auth-action:focus-visible,.button:focus-visible{outline:2px solid var(--ink);outline-offset:4px}
.auth-action:disabled,.button:disabled{opacity:.4;cursor:not-allowed}
.auth-action[aria-busy="true"],.button[aria-busy="true"]{opacity:.6;cursor:progress}
@media(prefers-reduced-motion:reduce){.auth-action,.auth-action>span:first-child,.button{transition:none}.auth-action:not(:disabled):active,.button:not(:disabled):active{transform:none}}
.auth-disclosure{margin:.25rem 0 0;max-width:100%}.auth-disclosure>summary{width:fit-content;min-height:44px;max-width:100%;padding:13px 0;line-height:18px;color:var(--muted);list-style-position:inside}.auth-disclosure>summary:hover{color:var(--ink)}.auth-disclosure p{color:var(--muted);margin:.5rem 0 1rem}.auth-disclosure .auth-actions{margin:0}
.x-profile{color:inherit;text-decoration:none;text-underline-offset:.18em}.x-profile:hover,.x-profile:focus-visible{text-decoration:underline}.x-profile:focus-visible{outline:2px solid currentColor;outline-offset:3px}
.gallery-card-copy .x-profile:focus-visible{outline-offset:-1px}
.claim-withdrawal{margin-top:1.5rem}.claim-withdrawal p{color:var(--ink)}
.claim-withdrawal [hidden]{display:none}.withdraw-dialog{width:min(400px,calc(100vw - 32px));max-height:calc(100dvh - 32px);margin:auto;padding:24px;border:1px solid var(--line);border-radius:4px;background:var(--paper);color:var(--ink);line-height:1.5;overflow:auto}.withdraw-dialog::backdrop{background:rgb(0 0 0 / .45)}.withdraw-dialog h2{margin:0}.withdraw-dialog p{margin:.75rem 0;overflow-wrap:anywhere}.withdraw-dialog .auth-actions{justify-content:flex-end;gap:.5rem 1rem;margin-top:1rem}.withdraw-dialog [aria-disabled="true"]{opacity:.6;cursor:wait}
.auth-accounts{border:0;margin:1.5rem 0 .25rem;padding:0;min-width:0}.auth-account{display:flex;align-items:center;gap:.75rem;min-height:44px;padding:.5rem 0;cursor:pointer}.auth-account>span{min-width:0;display:grid;justify-items:start;gap:.15rem}.auth-account-handle{padding:var(--tag-padding);border-radius:var(--tag-radius);line-height:var(--control-line-height)}.auth-account input{flex-shrink:0;width:12px;height:12px;margin:0;accent-color:var(--ink)}.auth-account input:checked+span .auth-account-handle{background:var(--paper-2)}.auth-disclosure>summary:focus-visible,.auth-account input:focus-visible{outline:2px solid var(--blue);outline-offset:3px}
footer{min-height:64px;border-top:1px solid var(--line);padding:.5rem 4vw;display:flex;flex-wrap:wrap;gap:.5rem 1rem;justify-content:space-between;align-items:center;color:var(--muted)}footer a{text-underline-offset:.2em}.footer-credit{min-width:0;line-height:1.6}.footer-credit a,.footer-credit span{white-space:nowrap}.footer-about{display:inline-flex;align-items:center;min-height:44px;margin-inline-start:auto;white-space:nowrap;text-decoration:none}.footer-about:hover{text-decoration:underline}.footer-about:focus-visible,.footer-credit a:focus-visible,.about-sheet a:focus-visible{outline:2px solid var(--blue);outline-offset:3px}
.footer-agent{display:inline-flex;align-items:center;gap:4px;min-height:44px;vertical-align:baseline;text-decoration:none}.footer-agent>span:not([aria-hidden]){text-decoration:underline}.footer-x-icon{display:block;width:12px;height:12px;flex:none}
.about-page{padding:5rem var(--page-gutter) 3rem}.about-sheet{width:100%;max-width:42rem;margin-inline:auto;line-height:1.7;overflow-wrap:anywhere}.about-sheet h1{max-width:none;margin:0 0 1.5rem;line-height:1.7;letter-spacing:normal}.about-sheet h2{margin:0 0 .5rem;line-height:1.7}.about-sheet p{margin:.75rem 0;color:var(--muted)}.about-sheet section{margin-top:2rem}.about-sheet a{text-underline-offset:.2em;white-space:nowrap}.about-sheet .auth-disclosure{margin-top:1.25rem}
/* Developer chrome floats above the page; it never reserves product layout space. */
.rehearsal-watermark{position:fixed;inset-block-start:max(8px,env(safe-area-inset-top));inset-inline-start:50%;transform:translateX(-50%);z-index:40;max-width:calc(100vw - 128px);color:var(--dev-ink);line-height:1.5;--dev-paper:#fff3d4;--dev-ink:#674200;--dev-border:#a47728;--dev-shadow:rgba(57,37,0,.18)}
.rehearsal-disclosure{margin:0}.rehearsal-disclosure>summary{display:flex;align-items:center;justify-content:center;gap:8px;min-height:44px;padding:6px 10px;border:1px dashed var(--dev-border);border-radius:8px;background:var(--dev-paper);box-shadow:0 2px 10px var(--dev-shadow);list-style:none;white-space:nowrap}.rehearsal-disclosure>summary::-webkit-details-marker{display:none}.rehearsal-disclosure>summary:focus-visible{outline:2px solid var(--dev-ink);outline-offset:3px}.rehearsal-disclosure[open]>summary{border-style:solid}.rehearsal-dev-badge{padding:0 4px;border-radius:3px;background:var(--dev-ink);color:var(--dev-paper);letter-spacing:.04em}
.rehearsal-context{position:absolute;inset-block-start:calc(100% + 8px);inset-inline-start:50%;transform:translateX(-50%);width:360px;max-width:calc(100vw - 24px);max-height:calc(100dvh - 80px - env(safe-area-inset-top));overflow-y:auto;overscroll-behavior:contain;padding:16px;border:1px dashed var(--dev-border);border-radius:8px;background:var(--dev-paper);box-shadow:0 8px 28px var(--dev-shadow);overflow-wrap:anywhere}.rehearsal-context p{margin:.65rem 0 0}.rehearsal-context .rehearsal-context-heading{margin:0 0 1rem;padding-bottom:.75rem;border-bottom:1px dashed var(--dev-border)}.rehearsal-context h2{margin:0}.rehearsal-context section+section{margin-top:1rem;padding-top:1rem;border-top:1px dashed var(--dev-border)}
.rehearsal-fixture-links{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 8px;margin-top:.5rem}.rehearsal-fixture-links a{display:flex;align-items:center;min-height:44px;min-width:0;border-radius:3px;text-decoration:none}.rehearsal-fixture-links a>span{padding:3px;border-radius:3px}.rehearsal-fixture-links a[aria-current="page"]>span{background:var(--dev-ink);color:var(--dev-paper)}.rehearsal-fixture-links a:hover>span{text-decoration:underline;text-underline-offset:.2em}.rehearsal-fixture-links a:focus-visible{outline:2px solid var(--dev-ink);outline-offset:1px}
@media(prefers-color-scheme:dark){.rehearsal-watermark{--dev-paper:#292114;--dev-ink:#f4ca7a;--dev-border:#a88443;--dev-shadow:rgba(0,0,0,.35)}}
@media(max-width:480px){.rehearsal-disclosure>summary>span:last-child{display:none}}
.gr0k-readout strong,.facts dd,.gallery-card-copy>span,.gallery-card-copy small,.signature-card span,.signature-card time,.mint-card-detail,.study-technical,time,code,pre{font-variant-numeric:tabular-nums}
/* One size and weight for every HTML surface, including mint review and studies.
   Keep rem-based layout at 16px; authored SVG typography is not interface text. */
body,body :not(svg,svg *){font-size:var(--ui-font-size);font-weight:400}

/* Keep the navigation tabs compact. Their 7px side padding balances
   the visible vertical space from 3px padding plus Instrument Sans line metrics. */
.gallery-tabs{display:flex;align-items:center;justify-content:center;gap:.5rem;min-height:44px;color:var(--ink)}.gallery-tabs a{display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:0 13px;color:inherit;text-decoration:none}.gallery-tabs a>span{padding:var(--tag-padding);border-radius:var(--tag-radius);line-height:var(--control-line-height)}.gallery-tabs a[aria-current="page"]>span{background:var(--paper-2)}.gallery-tabs a:focus-visible{outline:2px solid var(--blue);outline-offset:3px}
@media(max-width:820px){.public-gallery-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.collection-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.mint-review{grid-template-columns:1fr}.gallery-shell{min-height:680px}.mint-art{min-height:65vh}}
@media(max-width:600px){.book-page{--page-gutter:20px}.public-gallery-grid{grid-template-columns:minmax(0,1fr)}.collection-grid{grid-template-columns:minmax(0,1fr)}.slogan-signature-desktop{display:none}.slogan-signature-mobile{display:block}}
`;

// A normal page reload must not reuse CSS from an earlier build.
export const SITE_CSS_URL = `/assets/site.css?v=${createHash("sha256").update(SITE_CSS).digest("hex").slice(0, 16)}`;
