export const SITE_CSS = `
:root{color-scheme:light;--ink:#101319;--paper:#f4f0e6;--paper-2:#e7e0d2;--blue:#2557ff;--blue-hover:#153fe0;--line:rgba(16,19,25,.18);--muted:#625f59;--white:#fffdf8;--gallery-bg:#101319;--gallery-ink:#f4f0e6;--gallery-muted:#a9abae;--gallery-line:#343943;--stage:#d9dce5;--art-paper:#f2ead6;--art-shadow:rgba(16,19,25,.16)}
:root[data-theme="dark"]{color-scheme:dark;--ink:#f4f0e6;--paper:#101319;--paper-2:#242832;--blue:#7893ff;--blue-hover:#91a7ff;--line:rgba(244,240,230,.2);--muted:#aaa7a0;--white:#171b22;--gallery-bg:#080a0d;--gallery-ink:#f4f0e6;--gallery-muted:#a9abae;--gallery-line:#343943;--stage:#242832;--art-paper:#f2ead6;--art-shadow:rgba(0,0,0,.42)}
@media(prefers-color-scheme:dark){:root:not([data-theme="light"]){color-scheme:dark;--ink:#f4f0e6;--paper:#101319;--paper-2:#242832;--blue:#7893ff;--blue-hover:#91a7ff;--line:rgba(244,240,230,.2);--muted:#aaa7a0;--white:#171b22;--gallery-bg:#080a0d;--gallery-ink:#f4f0e6;--gallery-muted:#a9abae;--gallery-line:#343943;--stage:#242832;--art-paper:#f2ead6;--art-shadow:rgba(0,0,0,.42)}}
*{box-sizing:border-box}html{font-size:16px}body{margin:0;background:var(--paper);color:var(--ink);font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;min-height:100vh}a{color:inherit}
.fixture-banner{background:var(--blue);color:white;padding:.55rem 4vw;text-align:center;font:700 .75rem/1.2 ui-monospace,monospace;letter-spacing:.08em;text-transform:uppercase}
.site-header{min-height:76px;padding:.75rem 4vw;display:flex;align-items:center;justify-content:space-between;gap:1.5rem;border-bottom:1px solid var(--line)}.wordmark{text-decoration:none;font-weight:900;letter-spacing:-.05em;font-size:1.15rem}.wordmark span{color:var(--blue)}.header-actions{display:flex;align-items:center;gap:1.5rem}nav{display:flex;gap:1.5rem}nav a{font-size:.9rem;text-decoration:none}nav a:hover{text-decoration:underline}.theme-switcher{display:flex;margin:0;padding:.2rem;border:1px solid var(--line);border-radius:999px}.theme-switcher legend{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}.theme-option{appearance:none;border:0;background:transparent;color:var(--muted);border-radius:999px;padding:.38rem .62rem;font:700 .7rem/1 ui-monospace,SFMono-Regular,Consolas,monospace;letter-spacing:.03em;cursor:pointer}.theme-option:hover{color:var(--ink)}.theme-option[aria-pressed="true"]{background:var(--ink);color:var(--paper)}.theme-option:focus-visible{outline:2px solid var(--blue);outline-offset:2px}
main{min-height:calc(100vh - 140px)}.home-grid,.preview-grid{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(340px,.85fr);min-height:calc(100vh - 140px)}.intro-panel,.claim-panel{padding:clamp(2.5rem,7vw,7rem) 6vw}.intro-panel{border-right:1px solid var(--line)}
.eyebrow,.art-label,.gallery-index{font:700 .75rem/1.2 ui-monospace,SFMono-Regular,Consolas,monospace;letter-spacing:.12em;text-transform:uppercase}.eyebrow{color:var(--blue);margin:0 0 1.25rem}h1{font-family:Georgia,"Times New Roman",serif;font-size:clamp(3.2rem,7vw,7.5rem);line-height:.88;letter-spacing:-.065em;margin:0;max-width:10ch;font-weight:400}.lede{font-size:clamp(1.05rem,1.4vw,1.35rem);line-height:1.5;max-width:34rem;margin:2rem 0 3.5rem;color:var(--muted)}
.steps{list-style:none;padding:0;margin:0;border-top:1px solid var(--line);max-width:42rem}.steps li{display:grid;grid-template-columns:3rem 1fr;gap:1rem;padding:1.15rem 0;border-bottom:1px solid var(--line)}.steps li>span{font:700 .75rem ui-monospace,monospace;color:var(--blue)}.steps strong{font-size:1rem}.steps p{margin:.35rem 0 0;color:var(--muted);line-height:1.45}
.gallery-shell{background:var(--gallery-bg);color:var(--gallery-ink);padding:2rem 3vw;display:flex;flex-direction:column}.gallery-index{display:flex;justify-content:space-between;color:var(--gallery-muted)}.empty-frame{margin:auto;border:1px solid var(--gallery-line);min-height:360px;width:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:3rem}.empty-mark{color:var(--blue);font-size:4rem}.empty-frame h2{font:400 2rem Georgia,serif;margin:1rem 0 .5rem}.empty-frame p{color:var(--gallery-muted);max-width:24rem;line-height:1.5}.fixture-links{border-top:1px solid var(--gallery-line);padding-top:1.25rem;display:grid;gap:.75rem}.fixture-links>span{font:.7rem ui-monospace,monospace;color:var(--gallery-muted);text-transform:uppercase;letter-spacing:.1em}.fixture-links a{color:var(--gallery-ink);text-decoration:none}.fixture-links a:hover{text-decoration:underline}
details{margin-top:2rem}summary{cursor:pointer;font-weight:700}pre{white-space:pre-wrap;background:var(--white);border:1px solid var(--line);padding:1.25rem;font-size:.78rem;line-height:1.5;max-width:44rem;overflow:auto}
.art-stage{background:var(--stage);padding:2.5rem 4vw;display:flex;flex-direction:column;justify-content:center}.art-label{display:flex;justify-content:space-between;margin-bottom:1rem}.art-stage img{width:min(100%,680px);aspect-ratio:1;background:var(--art-paper);box-shadow:0 35px 80px var(--art-shadow);align-self:center}.claim-panel{display:flex;flex-direction:column;justify-content:center;background:var(--white)}.claim-panel h1{font-size:clamp(3.5rem,6vw,6.5rem)}
.gr0k-readout{margin:2.5rem 0;border-block:1px solid var(--line);padding:1.25rem 0;display:flex;align-items:baseline;justify-content:space-between}.gr0k-readout span{font:700 .8rem ui-monospace,monospace;text-transform:uppercase}.gr0k-readout strong{font:400 clamp(2rem,4vw,4rem) Georgia,serif;letter-spacing:-.04em}.trust-copy,.fine-print{line-height:1.55;color:var(--muted);max-width:32rem}.fine-print{font-size:.82rem;margin-top:1rem}
.button{display:inline-flex;justify-content:center;align-items:center;min-height:52px;background:var(--blue);color:white;border:1px solid var(--blue);padding:.8rem 1.35rem;text-decoration:none;font-weight:700;font-size:.9rem;cursor:pointer}.button:hover{background:var(--blue-hover)}.button.secondary{background:transparent;color:inherit;border-color:currentColor;margin-top:1rem}.message-page{padding:10vh 6vw}.message-page h1{font-size:8rem}.message-page p{font-size:1.1rem;max-width:35rem;line-height:1.5}
.review-wrap,.signature-page{display:grid;grid-template-columns:minmax(320px,1fr) minmax(360px,.8fr);min-height:calc(100vh - 140px)}.review-art,.signature-art{background:var(--stage);padding:5vw;display:flex;flex-direction:column;justify-content:center}.review-art img,.signature-art img{width:min(100%,620px);aspect-ratio:1;box-shadow:0 28px 70px var(--art-shadow);align-self:center}.review-copy,.signature-record{background:var(--white);padding:clamp(2.5rem,6vw,6rem);display:flex;flex-direction:column;justify-content:center}.review-copy h1{font-size:clamp(3rem,5vw,5.5rem)}.facts{margin:2rem 0;border-top:1px solid var(--line)}.facts>div{display:grid;grid-template-columns:minmax(8rem,.5fr) 1fr;gap:1rem;padding:.8rem 0;border-bottom:1px solid var(--line)}.facts dt{font-size:.75rem;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}.facts dd{margin:0;font:500 .78rem/1.45 ui-monospace,monospace;overflow-wrap:anywhere}.notice{border-left:3px solid var(--blue);padding:.2rem 0 .2rem 1rem;margin:1rem 0}.notice p{color:var(--muted);line-height:1.5}.quiet-link{margin-top:1.2rem;color:var(--muted);font-size:.85rem}.claim-line{font-weight:700}.provenance{margin-top:1rem}
.collection-head{padding:clamp(2.5rem,6vw,6rem) 5vw 2rem;display:flex;justify-content:space-between;align-items:end;border-bottom:1px solid var(--line)}.collection-head h1{font-size:clamp(3rem,6vw,6rem)}.collection-head p:last-child{color:var(--muted)}.collection-grid{padding:3vw 5vw 7vw;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:2rem}.signature-card{display:block;text-decoration:none;border-top:1px solid var(--ink);padding-top:.8rem}.signature-card img{display:block;width:100%;aspect-ratio:1;background:var(--art-paper);transition:transform .2s ease}.signature-card:hover img{transform:translateY(-4px)}.signature-card>div{display:grid;grid-template-columns:1fr auto;margin-top:.85rem;gap:.25rem 1rem}.signature-card strong{font-family:Georgia,serif;font-size:1.25rem}.signature-card span,.signature-card time{font:500 .75rem ui-monospace,monospace;color:var(--muted)}.signature-card time{grid-column:2;grid-row:1}.collection-empty{grid-column:1/-1;padding:8rem 0;text-align:center;border:1px solid var(--line)}
footer{min-height:64px;border-top:1px solid var(--line);padding:1rem 4vw;display:flex;justify-content:space-between;align-items:center;font-size:.75rem;color:var(--muted)}
@media(max-width:820px){.home-grid,.preview-grid,.review-wrap,.signature-page{grid-template-columns:1fr}.intro-panel{border-right:0;border-bottom:1px solid var(--line)}.gallery-shell{min-height:680px}.site-header{min-height:64px;align-items:flex-start;flex-direction:column}.header-actions{width:100%;justify-content:space-between;gap:.75rem}.site-header nav{gap:.85rem}.site-header nav a{font-size:.8rem}.theme-option{padding:.35rem .5rem}.art-stage,.review-art,.signature-art{min-height:65vh}.claim-panel,.review-copy,.signature-record{min-height:60vh}.collection-head{align-items:flex-start;gap:2rem;flex-direction:column}.collection-grid{grid-template-columns:1fr}footer{align-items:flex-start;gap:.5rem;flex-direction:column}}
@media(prefers-reduced-motion:no-preference){.art-stage img{animation:arrive .7s cubic-bezier(.2,.8,.2,1)}@keyframes arrive{from{opacity:0;transform:translateY(14px) scale(.985)}to{opacity:1;transform:none}}}
`;
