#!/usr/bin/env python3
"""Capture the fixed brand phrase through the unmodified, pinned v2 geometry.

This offline adapter is deliberately not an account-handle renderer: its only
input is the exact approved slogan literal. Public generate_svg validation stays
unchanged. No API calls or runtime Python are involved in the homepage.

Default / --check: verify the checked-in TypeScript snapshot without writing.
--emit: print the deterministic TypeScript module for a reviewed update.
--json: print the same capture as JSON for independent tests and inspection.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import sys

sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[1]
PYTHON_PATH = ROOT / "reference/algorithm-v2.0.1/signature_renderer_v2.0.1.py"
SNAPSHOT_PATH = ROOT / "src/brand/sloganMbtiFrames.ts"
PYTHON_SHA256 = "bfa7ebdfb6e5ced7ddc0b92c3facb3709863ee6c6d10cf9a2f1596c018ecb896"
UPSTREAM_COMMIT = "d00c018d1a740a5807480126d1f1bd0c620fb96d"
DISPLAY_TEXT = "The_First_Agent_Artwork"
MBTI_ORDER = ("ISTJ", "ISFJ", "INFJ", "INTJ", "ISTP", "ISFP", "INFP", "INTP")


def load_renderer():
    if hashlib.sha256(PYTHON_PATH.read_bytes()).hexdigest() != PYTHON_SHA256:
        raise ValueError("Pinned v2 Python renderer changed; refusing brand capture")
    spec = importlib.util.spec_from_file_location("signature_renderer_v2_brand_oracle", PYTHON_PATH)
    if spec is None or spec.loader is None:
        raise ValueError("Cannot load the pinned v2 Python renderer")
    renderer = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(renderer)
    return renderer


def brand_path(renderer, display_text: str, mbti: str) -> str:
    if display_text != DISPLAY_TEXT:
        raise ValueError("Brand adapter accepts only the exact slogan literal")
    profile = renderer.profile_for_mbti(mbti)
    layout = renderer.reusable_text_curve_layout(len(display_text))
    # Apply the upstream long-text policy before generating geometry. Never
    # stretch a finished path: handle lengths, Y values and stroke weights stay
    # canonical. Only anchor spacing and the horizontal canvas grow.
    profile["curve_span"] = layout["curve_span"]
    points = renderer.center_points_for_outline(renderer.geometry_for(display_text, profile), profile)
    shift_x = layout["canonical_width"] / 2 - renderer.CANONICAL_CENTER
    points = [renderer.shift_point_x(point, shift_x) for point in points]
    if profile["path_mode"] == "variable_bezier_outline":
        return renderer.bezier_variable_width_path(points, profile)
    return renderer.sampled_variable_width_path(points, profile)


def capture() -> dict:
    renderer = load_renderer()
    frames = []
    for mbti in MBTI_ORDER:
        paired_mbti = "E" + mbti[1:]
        path = brand_path(renderer, DISPLAY_TEXT, mbti)
        if path != brand_path(renderer, DISPLAY_TEXT, paired_mbti):
            raise ValueError(f"I/E geometry unexpectedly differs for {mbti}")
        frames.append({
            "mbti": mbti,
            "pairedMbti": paired_mbti,
            "d": path,
            "sha256": hashlib.sha256(path.encode("utf-8")).hexdigest(),
        })
    if len({frame["sha256"] for frame in frames}) != 8:
        raise ValueError("Expected eight distinct slogan geometries")
    return {
        "source": {
            "displayText": DISPLAY_TEXT,
            "rendererVersion": "sg-renderer-2.0.1",
            "upstreamCommit": UPSTREAM_COMMIT,
            "pythonSha256": PYTHON_SHA256,
            "adapter": "brand-only-whole-phrase-v2",
        },
        "layout": renderer.reusable_text_curve_layout(len(DISPLAY_TEXT)),
        "frames": frames,
    }


def module_text(result: dict) -> str:
    quote = lambda value: json.dumps(value, ensure_ascii=True)
    lines = [
        "// Generated by scripts/capture-slogan-v2.py --emit. Do not hand-edit path data.",
        "// Brand-only whole-phrase capture; public account-handle validation is unchanged.",
        "// Each I/E pair shares geometry. Presentation chooses color independently.",
        "export const SLOGAN_MBTI_SOURCE = Object.freeze({",
    ]
    lines += [f"  {key}: {quote(value)}," for key, value in result["source"].items()]
    lines.extend(["} as const);", "", "export const SLOGAN_MBTI_LAYOUT = Object.freeze({"])
    lines += [f"  {key}: {quote(value)}," for key, value in result["layout"].items()]
    lines.extend(["} as const);", "", "export const SLOGAN_MBTI_FRAMES = Object.freeze(["])
    for frame in result["frames"]:
        lines.append("  Object.freeze({")
        lines += [f"    {key}: {quote(value)}," for key, value in frame.items()]
        lines.append("  } as const),")
    lines += ["] as const);", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="Verify the checked-in snapshot (default)")
    mode.add_argument("--emit", action="store_true", help="Print a deterministic TypeScript snapshot")
    mode.add_argument("--json", action="store_true", help="Print source metadata and captured frames as JSON")
    args = parser.parse_args()
    result = capture()
    expected = module_text(result)
    if args.emit:
        sys.stdout.write(expected)
    elif args.json:
        print(json.dumps(result, separators=(",", ":")))
    else:
        if not SNAPSHOT_PATH.is_file() or SNAPSHOT_PATH.read_text(encoding="utf-8") != expected:
            raise ValueError("Slogan v2 snapshot differs; inspect --emit before accepting an update")
        print("Verified 8 pinned v2 slogan shapes and all I/E geometry pairs.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError) as error:
        print(str(error), file=sys.stderr)
        raise SystemExit(1)
